name: rawkit
description: A reusable Dart SDK for importing and developing camera RAW images.
version: 0.3.0
website: https://github.com/focale-editor/rawkit
repository: https://github.com/focale-editor/rawkit

environment:
  sdk: '>=3.13.0 <4.0.0'

platforms:
  linux:
  macos:
  web:
  windows:

executables:
  prepare_library: prepare_library

dependencies:
  code_assets: ^2.0.0
  crypto: ^3.0.7
  ffi: ^2.2.0
  hooks: ^2.2.0
  native_toolchain_c: ^0.19.4
  web: ^1.1.1
  zcodec: '>=0.2.0 <0.3.0'

dev_dependencies:
  lints: ^6.1.0
  release: ^0.1.11
  test: ^1.31.2

release:
  changelog:
    header: '# 📰 RawKit changelog'
    defaultIgnoredTypes: ['test']
    defaultIgnoredScopes: ['repo', 'docs', 'version', 'deps', 'tools']

flutter:
  assets:
    - path: assets/web/
      platforms:
        - web
